### ISSUE TITLE
the original images dataset for training SeqNet

### ISSUE THREAD

**Issue by Jinyu-M** [oravus/seqNet#1]
Hi, thanks for your remarkable work!
Could you please provide the original images dataset for training SeqNet? such as Nordland, Oxford, Brisbane, and MSLS? Thanks.

**Comment by oravus** [comment]
Hi, you can download the Nordland dataset imagery directly from [here](https://cloudstor.aarnet.edu.au/plus/s/8L7loyTZjK0FsWT). The Oxford and MSLS datasets can be downloaded from their original sources, [this](https://robotcar-dataset.robots.ox.ac.uk/) and [this](https://www.mapillary.com/dataset/places), respectively.

For the Nordland and Oxford datasets included in this repository, please refer to their `./structFiles`, for example, [oxford-v1.0_2015-03-17-11-08-44_2014-12-16-18-44-24_test_d-10_d2-5.db](structFiles/oxford-v1.0_2015-03-17-11-08-44_2014-12-16-18-44-24_test_d-10_d2-5.db). These are read using [parse_db_struct](https://github.com/oravus/seqNet/blob/3ce87a3651ba082872835cd508a47950460a4ea4/datasets.py#L130) and comprise `dbImage` and `qImage` fields referring to the original image names. 

NetVLAD descriptors corresponding to `dbImage` and `qImage` can be downloaded directly (see [download.sh](download.sh)).

For the Brisbane dataset, we can only release the descriptor data.

**Comment by Jinyu-M** [comment]
thanks for your kindly help :）
