### ISSUE TITLE
Train sequential descriptors through SeqNet on the MSLS dataset

### ISSUE THREAD

**Issue by fufj** [oravus/seqNet#12]
Hi! Thanks for your great work on SeqNet.
And I met a problem when I trained the sequential descriptors on the MSLS dataset. I just run the command: python main.py --mode train --pooling seqnet --dataset msls --msls_trainCity melbourne --msls_valCity austin --seqL 5 --w 3 --outDims 4096 --expName "msls_w3".
But ther is a problem: No such file or directory: './data/descData/netvlad-pytorch/msls_melbourne_databast.npy'.
Maybe I did not find any corresponding  ***.npy files about the MSLS dataset. Would you mind providing the corresponging download link of the MSLS dataset.?
Kind regards!

**Comment by oravus** [comment]
Hi @fufj, thanks for your interest.

You will need to extract single image descriptors first, instructions for which can be found [here](https://github.com/oravus/seqNet#single-image-vanilla-netvlad-extraction).

**Comment by fufj** [comment]
Thanks for your prompt reply. 
I will try it again.
