### ISSUE TITLE
"seqL_filterData" argument

### ISSUE THREAD

**Issue by kaiyi98** [oravus/seqNet#13]
Hi! Thanks for your great work!
The argument, “seqL_filterData”, has always defaulted to None,  What does it do and under what conditions is it used?
Kind regards!

**Comment by oravus** [comment]
Hi @kaiyi98, thanks for your interest.

That argument is optionally used to leave out some of the end indices of a traverse (e.g. Oxford dataset) as they may not have a valid sequence centred at those indices, which depends on the sequence length used. So, we can skip using some of the end point sequences for any purposes (in particular during evaluation). 

If `seqL_filterData` argument is passed with a value (typically equal to the `seqL`), [this](https://github.com/oravus/seqNet/blob/84aff4e9862ed1282a2c513dcaaa5e51335396b4/datasets.py#L252) part of the code will modify the dataset accordingly.

The default behaviour for the codebase (where `seqL_filterData` is None) is to push the sequence within limits, that is, when asked for sequence of length 5 at index 1 (or 0), it will provide the same sequence as it would for index 2. And similar behaviour at the other end index of the traverse. [This](https://github.com/oravus/seqNet/blob/84aff4e9862ed1282a2c513dcaaa5e51335396b4/datasets.py#L113) function implements this default behaviour.

Hope that helps.
