### ISSUE TITLE
Doubts about the descriptors

### ISSUE THREAD

**Issue by kaiyi98** [oravus/seqNet#15]
Hi! Thanks for your work!
I have some doubts about the nordland image descriptors.
1. The nordland image descriptors are from netvlad. Whether the netvlad model was trained in the nordland?
2. Which one is a fixed distance sample between oxford-pnv and oxford-v1.0

Kind regards!

**Comment by kaiyi98** [comment]
And then，I test oxford-v1.0 dataset using your oxford-v1.0_pretrained_l5_w3 model and get the reacall@1=0.7424 recall@5=0.8775 racall@20=0.9632. But the results in paper Table I are SeqNet(S5) recall@1/5/20=0.62/0.76/0.88.
I don't konw why. 
Thank you!

**Comment by oravus** [comment]
Hi @kaiyi98, 

> Hi! Thanks for your work! I have some doubts about the nordland image descriptors.
> 
> 1. The nordland image descriptors are from netvlad. Whether the netvlad model was trained in the nordland?

The provided single image descriptors are not trained on Nordland but Pittsburgh (30K). Please see [this](https://github.com/Nanne/pytorch-NetVlad) and [this](https://github.com/QVPR/Patch-NetVLAD) to train the model.

> 2. Which one is a fixed distance sample between oxford-pnv and oxford-v1.0

oxford-v1.0 has the fixed distance sampling. oxford-pnv refers to the data split as per the PointNetVLAD paper.

Hope that helps.

**Comment by oravus** [comment]
> And then，I test oxford-v1.0 dataset using your oxford-v1.0_pretrained_l5_w3 model and get the reacall@1=0.7424 recall@5=0.8775 racall@20=0.9632. But the results in paper Table I are SeqNet(S5) recall@1/5/20=0.62/0.76/0.88. I don't konw why. Thank you!

Both the results are valid. The difference is in the underlying trained model used for the purpose. In the paper, we mainly reported results by testing with models trained on a different city. So, in Table 1 there, Oxford results correspond to a model trained on Brisbane data and vice versa.

The results you obtained are expected to be better for Oxford as the model is trained on Oxford.

Hope that helps.

**Comment by kaiyi98** [comment]
> > And then，I test oxford-v1.0 dataset using your oxford-v1.0_pretrained_l5_w3 model and get the reacall@1=0.7424 recall@5=0.8775 racall@20=0.9632. But the results in paper Table I are SeqNet(S5) recall@1/5/20=0.62/0.76/0.88. I don't konw why. Thank you!
> 
> Both the results are valid. The difference is in the underlying trained model used for the purpose. In the paper, we mainly reported results by testing with models trained on a different city. So, in Table 1 there, Oxford results correspond to a model trained on Brisbane data and vice versa.
> 
> The results you obtained are expected to be better for Oxford as the model is trained on Oxford.
> 
> Hope that helps.

Thank you! Can you tell me how to align the gps timestamps and the stereo.timestamps for Oxford RobotCar.
