### ISSUE TITLE
MSLS austin/melbourne image number difference between original seq_info.csv and provided seqBounds.txt here 

### ISSUE THREAD

**Issue by lijincheng2020** [oravus/seqNet#17]
I find that the number of images in original seq_info.csv and the number of images in seqBounds.txt in this code are not the same.

For example, in melbourne/query/seq_info.csv (original MSLS dataset) there are 88119 images but here in structFiles/seqBoundsFiles/msls_melbourne_query_seqBounds.txt only 4474! This is the same case for austin city, but for amman it's the same.

I wonder whether some of you know the reason about this difference...

Thanks a lot!!!

**Comment by oravus** [comment]
Hi @lijincheng2020, we only use a subset of the original Melbourne and Austin traverses. Amman is used as is, given its small size. You can find the files with imagenames [here](https://github.com/oravus/seqNet/tree/main/structFiles/imageNamesFiles). Hope that helps.
