### ISSUE TITLE
Doubt regarding MSLS sequences

### ISSUE THREAD

**Issue by divyagupta25** [oravus/seqNet#18]
Hi, thanks for sharing your work! I have two doubts reagrding the MSLS sequences. 

1. In the paper, it is mentioned that for MSLS, the sequences were used as such. I checked the seqBound txt files and the sequence length seems to span hundreds of frames and is not fixed. However, it is said that the focus is on shorter sequences for VPR. Could you please explain this?
2. It is also mentioned in the paper that for all sequences, only those images are considered where a valid sequence can be 'centered'. However, looking at the seqBound txt files, it looks like the approach of taking the neighboring frames keeping the current frame as center is not used and the same frames are used for all frames in the sequence (e.g. 1 to 31 for all 31 frames). Could you please explain this as well?

Thanks in advance!

**Comment by oravus** [comment]
Hi @divyagupta25

> for MSLS, the sequences were used as such

This is from Section IV-B of the paper and in the context of intra-sequence frame separation: Brisbane and Oxford traverses were subsampled to keep consecutive frames 2m apart but for MSLS no such preprocessing was done to avoid changing its sequence characteristics.

> seqBound txt files and the sequence length seems to span hundreds of frames and is not fixed

Unlike Oxford and Brisbane datasets' continuous traverses, MSLS is a collection of several sequences where each such sequence is of variable length and geographically far from other sequences. `*_seqBounds.txt` files have lower and upper bound indices as two columns. These bounds do not define sequence length but are used to prevent sampling an L-length subsequence that might overlap two different sequences.  

> the focus is on shorter sequences for VPR

Yes, we use 5 frame sequences in most cases

I think your second question gets answered too by the above explanation.
Hope that helps.

**Comment by divyagupta25** [comment]
Thanks for your reply! 
So seqBounds are meaningful only in the case of MSLS and not other datasets which have continuous traverses.

**Comment by divyagupta25** [comment]
Thanks again!
