### ISSUE TITLE
Related files for msls experiments

### ISSUE THREAD

**Issue by lijincheng2020** [oravus/seqNet#19]
@oravus Hi! Thanks for your kindly reply in issue #17! That do help me a lot!

In case my additional comments in issue #17 are not noticed I submit this new issue and copy my question here:

In the experiments on MSLS dataset (Fig.4 in the paper), Amman, Boston, San Francisco and Copenhagen are used for testing but only files related Amman are provided (imageNames .txt and seqBounds.txt), for the rest three cities should I use subsets like your descriptions above? In this case could you please provide these related files so that I could do some experiments and get the same results? As the principle to generate those subsets was not mentioned in the paper:).

Or it is sufficient to generate these files myself from MSLS dataset, which means, to use the whole set of original Boston, San Francisco and Copenhagen traverses.

Thank you again!

**Comment by oravus** [comment]
> Or it is sufficient to generate these files myself from MSLS dataset, which means, to use the whole set of original Boston, San Francisco and Copenhagen traverses.
Yes, we used all the images from these traverses, so separate image file names are not required and you can directly use them from the MSLS data.
