### ISSUE TITLE
The evaluation metric about Precision@K

### ISSUE THREAD

**Issue by fufj** [oravus/seqNet#20]
Hi! Thanks for your great work on SeqNet.
The evaluation metric in SeqNet is only Recall@K, but the false positive instances is not considered.
Would you mind providing some implementation ideas in test step for evaluating the Precision@K?
Best wishes!

**Comment by oravus** [comment]
Hi @fufj, please refer to [this](https://github.com/mapillary/mapillary_sls/blob/main/mapillary_sls/utils/eval.py) code for precision based evaluation.
