### ISSUE TITLE
the Oxford dataset Preprocessing

### ISSUE THREAD

**Issue by Steven-jiaqi** [oravus/seqNet#21]
Thank you very much for your great work! Can you provide a version of the Oxford dataset that is the same as the clean Nordland dataset?
I'm sorry to bother you.

**Comment by oravus** [comment]
Hi @Steven-jiaqi, you can find subsampled imagename files for Oxford [here](https://github.com/oravus/seqNet/tree/main/structFiles/imageNamesFiles).

**Comment by Steven-jiaqi** [comment]
Thanks for the reply, but the photos I downloaded of the Oxford dataset were grayscale plots, not color plots, which struck me as odd.Can you give me some help on this?

**Comment by oravus** [comment]
> Oxford dataset were grayscale plots

If this is about the raw images, you will need to use [robotcar-dataset-sdk](https://github.com/ori-mrg/robotcar-dataset-sdk) to preprocess those images. You can also check this [file](https://github.com/mingu6/ProbFiltersVPR/blob/master/src/data/ready_images.py) (from a collaborator's repository) as a convenience wrapper.

**Comment by Steven-jiaqi** [comment]
Can you provide the original images of the Oxford dataset that you processed, I noticed that you tweaked the dataset in your paper and I couldn't reproduce the results with the original Oxford dataset.
I'm sorry to bother you.

**Comment by oravus** [comment]
Hi @Steven-jiaqi , sorry I don't have the preprocessed images with me. However, using this [code](https://github.com/mingu6/ProbFiltersVPR/blob/master/src/data/ready_images.py) for image preprocessing, it should be possible to reproduce results as the exact Oxford image timestamps are provided [here](https://github.com/oravus/seqNet/tree/main/structFiles/imageNamesFiles).
