### ISSUE TITLE
nGPU

### ISSUE THREAD

**Issue by Steven-jiaqi** [oravus/seqNet#22]
I'm sorry to bother you.
I've noticed that the 'nGPU' parameter only appears once in the main function, not anywhere else.I would like to know how this parameter is used.
Best wishes to you!

**Comment by oravus** [comment]
Hi @Steven-jiaqi, I might have removed the usage of nGPU but if you are interested you can refer to [this repo](https://github.com/Nanne/pytorch-NetVlad) to use multiple GPUs for training.
