### ISSUE TITLE
Broken links for pre-trained models and dataset

### ISSUE THREAD

**Issue by ur10** [oravus/seqNet#23]
Hello @oravus , thanks for your work. I was trying to run the method locally but I find that links provided for -
1. Dataset Download - https://cloudstor.aarnet.edu.au/plus/s/8L7loyTZjK0FsWT
2. Pre-trained models - https://cloudstor.aarnet.edu.au/plus/s/wx0zIGi3WBTtq5F are broken. Could you please provide the updated links? Thanks in advance.

**Comment by oravus** [comment]
Hi @ur10 , thanks for pointing. Dataset should hopefully be up in a couple of days and the pretrained models shortly after that.

**Comment by oravus** [comment]
Hi @ur10, please find the links [here](https://github.com/oravus/seqNet?tab=readme-ov-file#news). Thanks!
