### ISSUE TITLE
pre-train for MCD dataset

### ISSUE THREAD

**Issue by snakehaihai** [oravus/seqNet#24]
Hi Dr. Garg
We recently came up with a new challenging dataset called https://mcdviral.github.io/

We'd like to invite you to try the SeqNet on these 3 campuses located at different latitudes. 

if you have other IROS paper for me to review, I'm perfectly ok to do so 

Regards
Shenghai Yuan

**Comment by oravus** [comment]
Thanks @snakehaihai, the dataset looks quite interesting. Also, thanks for offering to help with IROS, I will reach out for relevant works. 
Cheers!
