### ISSUE TITLE
Could you tell me how to create . db file？

### ISSUE THREAD

**Issue by LLYYQJ** [oravus/seqNet#26]
Hello, thank you for your outstanding contribution and selfless sharing. I want to develop my own dataset for localization, but I encountered difficulties in the data preprocessing stage. I don't know how to generate. db files in the structFiles folder. I am confused about how to generate three db files for the Nordland dataset. Can you tell me where to learn how to create them? Thank you.

**Comment by oravus** [comment]
Hi @LLYYQJ , 
You can refer to [this](https://github.com/oravus/seqNet/issues/3#issuecomment-1006598225) for creating/reading dbStruct. If you read through the discussion on that issue and follow the links to other repositories, I think that will answer most of your queries.

Cheers!

**Comment by LLYYQJ** [comment]
Thank you for pointing out the key points.  I have reviewed the previous issue, but I am not very careful. I will try to build on this foundation. Thank you again for your valuable work.
