### ISSUE TITLE
Pretrained NetVLAD + PCA model link broken

### ISSUE THREAD

**Issue by Idanlau** [oravus/seqNet#28]
Hey Sourav thanks for your great work with seqNet. I noticed the linked you provided for the pretrained NetVLAD + PCA model doesn't work:
https://cloudstor.aarnet.edu.au/plus/s/gJZvogRj4FUUQMy/download

Would you mind updating it?

I found this on hugging face, is this the one?
https://huggingface.co/TobiasRobotics/Patch-NetVLAD/tree/main

**Comment by oravus** [comment]
yes, that should be it.
