### ISSUE TITLE
Questions about training and testing Seqnet using other dataset

### ISSUE THREAD

**Issue by XinLan12138** [oravus/seqNet#3]
Hi! I am now working on your SeqNet project, and meeting some problems through it.
Currently I can run the codes and get recall results using nordland and oxford dataset. Now I am trying to use other datasets like hilti: https://hilti-challenge.com/dataset.html  . I wonder how I can fit this dataset into your program. 
Should I also generate .db AND .npy files as well?  If my original data format is .jpg, what should be my process? the .npy files under /netvlad-pytorch file are descriptors generated by netVLAD, am I right?

Thank you for your patience and waiting for your kindly help!

**Comment by oravus** [comment]
Hi @XinLan12138, 

For using any other dataset, you are right about generating .db (for training) and .npy (global descriptors) files.

Regarding global descriptors .npy files:
We used [Nanne/pytorch-NetVlad](https://github.com/Nanne/pytorch-NetVlad) repo to generate global descriptors using their pittsburgh trained model. You can also use our [Patch-NetVLAD](https://github.com/QVPR/Patch-NetVLAD) repo to do the same. I will be updating this (SeqNet) repo by tomorrow integrating global descriptor extraction using Patch-NetVLAD.

**Comment by XinLan12138** [comment]
> 

Oh! Thanks for updating! I will read through the updates once you finished. BTW, how can I generate .db? Is that also included in the repo?

**Comment by oravus** [comment]
Generating .db is not currently in the repo. The easiest way of creating them is by using the [dbStruct declaration](https://github.com/oravus/seqNet/blob/5a678c2b4266b6f590385e5d16e4135daffc6571/datasets.py#L15) and then calling it as:

`db = dbStruct(splitName, datasetName, dbImageList, utmDb, qImageList, utmQ, numDb, numQ,
                                   d, d**2, d2**2, None, None, None, None)`,

which can then be saved and parsed using [save_db_struct](https://github.com/oravus/seqNet/blob/5a678c2b4266b6f590385e5d16e4135daffc6571/datasets.py#L178) and [parse_db_struct](https://github.com/oravus/seqNet/blob/5a678c2b4266b6f590385e5d16e4135daffc6571/datasets.py#L130) functions.

**Comment by oravus** [comment]
Hi @XinLan12138,

Single image descriptor extraction is now enabled, please see [this Readme subsection](https://github.com/oravus/seqNet#single-image-vanilla-netvlad-extraction).

**Comment by XinLan12138** [comment]
> Hi @XinLan12138,
> 
> Single image descriptor extraction is now enabled, please see [this Readme subsection](https://github.com/oravus/seqNet#single-image-vanilla-netvlad-extraction).

Hi @oravus , I have seen it and currently trying to extract the feature of pittsburgh250k dataset. It seems to process well now. process as follows:
//////////////////////
 python feature_extract.py --config_path patchnetvlad/configs/seqnet.ini --dataset_file_path /home/lx/lx/new_seqnet_data/pitts250k.txt --dataset_root_dir /home/lx/lx/new_seqnet_data --output_features_fullpath ../../data/descData/netvlad-pytorch/pitts250k.npy
Namespace(config_path='patchnetvlad/configs/seqnet.ini', dataset_file_path='/home/lx/lx/new_seqnet_data/pitts250k.txt', dataset_root_dir='/home/lx/lx/new_seqnet_data', nocuda=False, output_features_dir='/home/lx/lx/seqNet/thirdparty/Patch-NetVLAD/patchnetvlad/output_features', output_features_fullpath='../../data/descData/netvlad-pytorch/pitts250k.npy')
Parsing dataset...
Done! Found 254064 images
=> loading checkpoint '/home/lx/lx/seqNet/thirdparty/Patch-NetVLAD/patchnetvlad/./pretrained_models/pitts_orig_WPCA4096.pth.tar'
=> loaded checkpoint '/home/lx/lx/seqNet/thirdparty/Patch-NetVLAD/patchnetvlad/./pretrained_models/pitts_orig_WPCA4096.pth.tar'
====> Extracting Features
/////////////////////

However, I do not have oxford dataset as your dataset_root_dir so I can't reproduce the .npy as you. Can you send a copy of the source of Oxford dataset?

Also, regarding the generation of .db files, should I just write a python file to execute the two functions —— save_db_struct and parse_db_struct functions? Sorry for disturbance but I am new in this area :) Thank you for your help!

**Comment by oravus** [comment]
The Oxford Robotcar dataset is already public (and its re-hosting might be restricted by its license). You can download particular traverses (and sensor/camera types) from [here](https://robotcar-dataset.robots.ox.ac.uk/datasets/) and use [their official sdk](https://github.com/ori-mrg/robotcar-dataset-sdk) to convert images to RGB format. Please refer to the imagenames files for this dataset specific to our project [here](https://github.com/oravus/seqNet/tree/main/structFiles/imageNamesFiles).

If you are only meaning to test SeqNet on a readily available public dataset, you can download the Nordland dataset from [here](https://cloudstor.aarnet.edu.au/plus/s/8L7loyTZjK0FsWT).

For .db files, you can import those functions in your python project, then create and save the dbstruct as per your requirement.

As you are using Pitts250K probably only to test feature extraction part, you would ideally need a sequence-based dataset for SeqNet.

**Comment by oravus** [comment]
Hi @XinLan12138, please feel free to re-open if need be. Cheers!

**Comment by XinLan12138** [comment]
Hi, @oravus . Thank you for your quick reply. I have downloaded oxford dataset of 2014-12-16-18-44-24 and nordland dataset. Also, I tried to figure out how to generate .db files under ./structFiles. But things show that I only get the image list and corresponding images. No _utmDb, utmQ, posDistThr, nonTrivPosDistSqThr_  can be found to construct the .db file. 

I also downloaded pitts 250k from https://data.ciirc.cvut.cz/public/projects/2015netVLAD/Pittsburgh250k/ , in ./groundtruth files, I can get several these data but still do not know how to extract the .db.  Maybe could u plz update a little more in repository on these part so that we can understand more about the adaption to other dataset using Seqnet if you re free? Or could you explain a bit more to help me out? 

Besides, in your SeqNet paper GPS information is needed, is that represents for the utmDb and tumQ parameter?

Thanks for your patience and help to my project!!!

**Comment by oravus** [comment]
Yes, the GPS information is stored as utmDb and utmQ. It is also 'abused' a bit when using the Nordland dataset; there, it represents the image index since the Nordland dataset traverses are exactly aligned, thus Nordland evaluation is done in terms of frames instead of meters (based on utm).

Regarding terminology and meaning of other parameters in db files, see https://github.com/Nanne/pytorch-NetVlad/issues/26 and  https://github.com/Nanne/pytorch-NetVlad/issues/50, we follow the same convention for SeqNet. You can take help from that repository to process Pittsburgh dataset.

I am planning to release a seqnet feature extraction code, which might help solve part of your requirements with regards to testing any external traverse-based dataset.

**Comment by XinLan12138** [comment]
> 

OK, I will check pytorch-NetVlad codes for references. And waiting for your newly updated codes! :)

**Comment by snakehaihai** [comment]
> Generating .db is not currently in the repo. The easiest way of creating them is by using the [dbStruct declaration](https://github.com/oravus/seqNet/blob/5a678c2b4266b6f590385e5d16e4135daffc6571/datasets.py#L15) and then calling it as:
> 
> `db = dbStruct(splitName, datasetName, dbImageList, utmDb, qImageList, utmQ, numDb, numQ, d, d**2, d2**2, None, None, None, None)`,
> 
> which can then be saved and parsed using [save_db_struct](https://github.com/oravus/seqNet/blob/5a678c2b4266b6f590385e5d16e4135daffc6571/datasets.py#L178) and [parse_db_struct](https://github.com/oravus/seqNet/blob/5a678c2b4266b6f590385e5d16e4135daffc6571/datasets.py#L130) functions.

Hi thx for your work.

If I understand correctly, you only need to call db=dbStruct.... to create a new DB right?

May I know what the expected field in splitName, datasetName, dbImageList, utmDb, qImageList, utmQ, numDb, numQ, d, d**2, d2**2,

The imagelist should be a txt file containing all the image
UTM can be txt or csv files that contain x and y locations right?
and num* should be integer number

What's the d  d**2 and d2**2?

**Comment by oravus** [comment]
Hi @snakehaihai,

`d` and `d2` are `posDistSqThr`, `nonTrivPosDistSqThr` as explained [here](https://github.com/Nanne/pytorch-NetVlad/issues/50#issuecomment-778761874). We use `d` and `d2` as shorthand variables to name the `.db` files. I have updated this information in my earlier comment as well.

For a more detailed understanding of a `.db` file and the `namedtuple (dbStruct)`, you can try the following:
```python
from datasets import  parse_db_struct
my_db =  parse_db_struct('./structFiles/oxford-v1.0_2015-03-17-11-08-44_2014-12-16-18-44-24_test_d-10_d2-5.db')
[print('\033[1m' + k + '\033[0m', v[:10] if type(v) is list else v) for k,v in my_db._asdict().items()]
```

Hope that helps!
